In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# 设置中文字体（以SimHei为例）
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False  # 解决负号无法显示的问题

In [7]:
file_path = '预测销售值.xlsx'
data1 = pd.read_excel(file_path, sheet_name=0)
data1

,销售日期,水生根茎类,花叶类,花菜类,茄类,辣椒类,食用菌
0,2023-07-01,29.222461,186.294968,28.503189,31.825450,119.660045,72.102375
1,2023-07-02,22.937576,173.654405,23.944550,32.645951,103.688905,59.842886
2,2023-07-03,11.775991,114.176775,13.251859,20.741704,67.597678,36.042030
3,2023-07-04,9.880906,120.408629,13.119730,18.702127,66.699432,32.385753
4,2023-07-05,12.898367,116.249883,13.798858,18.663184,66.797620,39.361471
5,2023-07-06,14.964531,118.790013,16.049753,18.617662,75.115355,42.128869
6,2023-07-07,17.550108,128.935836,18.713546,21.613278,88.122527,52.557984

In [9]:
file_path = '单位成本预测.xlsx'
data2 = pd.read_excel(file_path, sheet_name=0)
data2

        销售时间      水生根茎类       花叶类       花菜类        茄类       辣椒类       食用菌
0 2023-07-01  10.995492  3.184934  7.888465  4.727423  3.615438  4.235932
1 2023-07-02  11.918336  3.209532  7.997031  4.612519  3.581469  3.985238
2 2023-07-03  11.623322  3.210043  8.004493  4.616401  3.601384  4.109135
3 2023-07-04  11.725731  3.210553  7.926001  4.672960  3.618806  4.149437
4 2023-07-05  11.698449  3.211063  7.882191  4.665132  3.627449  4.136085
5 2023-07-06  11.713489  3.211573  7.920259  4.641429  3.599147  4.134818
6 2023-07-07  11.714718  3.212083  7.971908  4.650793  3.583744  4.141236

In [17]:
def profit1(x,c):
    p = 3.856+0.462*x-0.253*c
    return p

x1 = data1['水生根茎类']
c1 = data2['水生根茎类']
w = []

for i, j in zip(x1, c1):
    p = profit1(i, j)
    w.append(p)

print('水生根茎类蔬菜的日利润为')
print(w)

print('水生根茎类蔬菜的日利润率为')
print(w/x1)

水生根茎类蔬菜的日利润为
[14.574917316183546, 11.4378211030624, 6.3558072884891486, 5.4543686156820925, 6.855337973755592, 7.8061008012747655, 9.00032606646782]
水生根茎类蔬菜的日利润率为
0    0.498757
1    0.498650
2    0.539726
3    0.552011
4    0.531489
5    0.521640
6    0.512836
Name: 水生根茎类, dtype: float64

In [15]:
def profit2(x,c):
    p = -34.736+0.991*x+16.562*c
    return p

x2 = data1['花叶类']
c2 = data2['花叶类']
w = []

for i, j in zip(x2, c2):
    p = profit1(i, j)
    w.append(p)

print('花叶类蔬菜的日利润为')
print(w)

print('花叶类蔬菜的日利润率为')
print(w/x2)

花叶类蔬菜的日利润为
[135.54267823629547, 126.32256121471212, 83.08169295152183, 87.61161910706731, 84.58758011458545, 86.43362370503651, 93.80900525035419]
花叶类蔬菜的日利润率为
0    0.727570
1    0.727437
2    0.727658
3    0.727619
4    0.727636
5    0.727617
6    0.727563
Name: 花叶类, dtype: float64

In [16]:
def profit3(x,c):
    p = 16.646+0.624*x-2.555*c
    return p

x3 = data1['花菜类']
c3 = data2['花菜类']
w = []

for i, j in zip(x3, c3):
    p = profit1(i, j)
    w.append(p)

print('花菜类蔬菜的日利润为')
print(w)

print('花菜类蔬菜的日利润率为')
print(w/x3)

花菜类蔬菜的日利润为
[15.009787430193464, 11.56136054992399, 3.778544165762378, 3.779579994372872, 4.32749947411102, 5.91680930987506, 7.789497563379223]
花菜类蔬菜的日利润率为
0    0.526600
1    0.482839
2    0.285133
3    0.288084
4    0.313613
5    0.368654
6    0.416249
Name: 花菜类, dtype: float64

In [18]:
def profit4(x,c):
    p = 6.144+0.582*x-0.956*c
    return p

x4 = data1['茄类']
c4 = data2['茄类']
w = []

for i, j in zip(x4, c4):
    p = profit1(i, j)
    w.append(p)

print('茄类蔬菜的日利润为')
print(w)

print('茄类蔬菜的日利润率为')
print(w/x4)

茄类蔬菜的日利润为
[17.3633198684563, 17.771461938557582, 12.270717585872251, 11.314123959097834, 11.298112894980644, 11.28307858841326, 12.664683902768736]
茄类蔬菜的日利润率为
0    0.545580
1    0.544370
2    0.591596
3    0.604965
4    0.605369
5    0.606042
6    0.585968
Name: 茄类, dtype: float64

In [19]:
def profit5(x,c):
    p = 90.316+1.1*x-23.307*c
    return p

x5 = data1['辣椒类']
c5 = data2['辣椒类']
w = []

for i, j in zip(x5, c5):
    p = profit1(i, j)
    w.append(p)

print('辣椒类蔬菜的日利润为')
print(w)

print('辣椒类蔬菜的日利润率为')
print(w/x5)

辣椒类蔬菜的日利润为
[58.224234893455325, 50.854162451854684, 34.174976931757115, 33.755579671844664, 33.79875587958029, 37.64870973000263, 43.66192018867312]
辣椒类蔬菜的日利润率为
0    0.486580
1    0.490449
2    0.505564
3    0.506085
4    0.505987
5    0.501212
6    0.495468
Name: 辣椒类, dtype: float64

In [20]:
def profit6(x,c):
    p = 4.046+0.727*x-1.237*c
    return p

x6 = data1['食用菌']
c6 = data2['食用菌']
w = []

for i, j in zip(x6, c6):
    p = profit1(i, j)
    w.append(p)

print('食用菌蔬菜的日利润为')
print(w)

print('食用菌蔬菜的日利润率为')
print(w/x6)

食用菌蔬菜的日利润为
[36.09560649960814, 30.495148122657234, 19.4678066319494, 17.768410526713353, 20.99457001335811, 22.273428367021843, 27.090056236350236]
食用菌蔬菜的日利润率为
0    0.500616
1    0.509587
2    0.540142
3    0.548649
4    0.533379
5    0.528698
6    0.515432
Name: 食用菌, dtype: float64